### ISSUE TITLE
Cute pink light theme doesn't appear in the appearance > theme menu

### ISSUE THREAD

**Issue by SamiYuisp** [openmindculture/intellij-cute-pink-dark-theme#9]
I have installed the plugin but it doesn't work
I have android studio Electric Eel | 2022.1.1 Patch 1

**Comment by openmindculture** [comment]
Hi, sorry to hear. Did you install and activate, and then choose it from Settings Appearance?
Does your IDE use the new UI or the classic one? Maybe you can add a screenshot?

**Comment by openmindculture** [comment]
Hi @SamiYuisp do you still have problems building the theme? Otherwise can we close this issue?
